### ISSUE TITLE
Distribute Via JCenter

### ISSUE THREAD

**Issue by sdoward** [jiefly/AbilityChart#2]
Nice project! 

I would love to be able to use this via jcenter. Do you think you guys will ever do that? If not I might fork and do it myself. What do you thinik?

**Comment by jiefly** [comment]
Thankyou for you suggestion.Today i will add this project in jcenter and add address in README.

**Comment by sdoward** [comment]
Great, you should probably extract the View as a module in the project first then make that available then your Activity can be an example of how to use it.

**Comment by jiefly** [comment]
you can use this view by  compile 'com.gao.jiefly:abilitychartlibrary:1.0.1'

**Comment by sdoward** [comment]
very nice! thanks
